### ISSUE TITLE
Backend function signatures are not compatible

### ISSUE THREAD

**Issue by adamwight** [CoderKungfu/php-queue#37]
For example, Memcache::add() takes arguments (key, data, expiry), but Base::add() and IronMQ::add() start with the $data argument.  It seems like the right thing to do is change the signature in Memcache::add to start with $data.

**Comment by miccheng** [comment]
Hmm... Would have to see how we can make sure it doesn't break backward
compatibility. Memcache is a key-value store. The rest are not like that. :/

**Comment by adamwight** [comment]
I was thinking that different backends could implement some new interfaces depending on their design, e.g. MessageQueue vs MessageKeyValueStore, but it seems pretty common that a backend could support both styles of access.

I'm not sure how to deal with the backwards compatibility thing, either.  Maybe deprecate add() and introduce set(k,v) and push(v)?

**Comment by miccheng** [comment]
Thanks. The interface sounds like a sensible approach. Deprecating add() is
good - perhaps forwarding it to push() by default (with an deprecation
error log) and throwing an exception if there's more than 1 arg (which
would have been a set anyways).

**Comment by adamwight** [comment]
Oops, I missed your message.  Here's a rough patch, I'll refine a bit tomorrow.  Please mention if you see anything I should do differently!

https://github.com/adamwight/php-queue/tree/queue_vs_kv

**Comment by miccheng** [comment]
Nothing that jumps out as "danger" to me. Just sad face to see so many FIXME and TODO. :(

**Comment by adamwight** [comment]
Ping!  Just letting you know PR #43 is ready for review, at your convenience.  Thanks!

**Comment by miccheng** [comment]
Thanks! Sorry, had been busy this few weeks at work.

**Comment by adamwight** [comment]
I badly confused myself while implementing IndexedFifoQueue, but I think I finally have a correct prototype.  It uses two separate indexes to provide the different access styles: https://github.com/adamwight/php-queue/pulls

BTW, what's your preferred communication medium?  Do you do IRC?  Sorry to necrobump this thread.

**Comment by miccheng** [comment]
Can try DM me on Twitter?
