### ISSUE TITLE
Consolidate return-value vs exception throwing

### ISSUE THREAD

**Issue by adamwight** [CoderKungfu/php-queue#41]
There is some tension between the queue backend functions which return true and throw exceptions.  If there is no way to return false, then calling code will include redundant error handling for no good reason.

However, voiding the return value will probably break existing code.  We can leave the "return true" until this usage is deprecated...

Do you agree that we should throw a JobNotFound exception whenever get($key) or pop() fails to find a message?

**Comment by miccheng** [comment]
Throwing exceptions at the wrong place crashes job runners. So i was a little hesitant to throw exceptions everywhere. I was hoping to let exceptions bubble up and catch it at the top most call before hitting user's code.

**Comment by adamwight** [comment]
Good point!  I tried to keep this in mind while working on #37, exceptions are only thrown when there are real errors.  Failure to retrieve a job using pop(), get(), or clear() will return a null value, but push() or set() failure throws an exception.  I think this will be mostly compatible with job runners that use the previous interface.
